# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'SwiftUIWebView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'

  # Pods for SwiftUIWebView

  target 'SwiftUIWebViewTests' do
    inherit! :search_paths
    # Pods for testing
	# Add the Firebase pod for Google Analytics
    
  end

  target 'SwiftUIWebViewUITests' do
    # Pods for testing
  end

end
